CREATE TABLE USERS
(
    id                INTEGER PRIMARY KEY AUTO_INCREMENT,
    CREATED_TIME      TIMESTAMP,
    UPDATE_TIME       TIMESTAMP,
    ENABLED           BOOLEAN,
    FIRST_NAME        VARCHAR,
    LAST_NAME         VARCHAR,
    PASSWORD          VARCHAR,
    REFRESH_TOKEN     VARCHAR,
    TOKEN_EXPIRY_DATE TIMESTAMP,
    USER_UUID         VARCHAR,
    USERNAME          VARCHAR,
    LANGUAGE_ID       VARCHAR,
    CONSTRAINT FK_Language FOREIGN KEY (Language_Id)
        REFERENCES LANGUAGE (ID)
);